/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * Generated by convex@1.41.0.
 * Committed here so the front end builds without a live Convex deployment;
 * `npx convex dev` will regenerate it once the backend is connected.
 */
import { anyApi } from "convex/server";

export const api = anyApi;
export const internal = anyApi;
